const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store,emptyDay}=require('../src/store.cjs');
const key='2026-09-08',rows=['Walk','Write','Read'].map(text=>({text,done:true})),extras=[{text:'Water plants',done:false}];
function fixture(){const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'three-clear-')),'priorities.json'),store=new Store(file);store.save(key,rows,'day',extras);store.save('2026-09-07',rows,'week',extras);store.save('2026-09-01',rows,'month',extras);store.save('2026-09-06',rows,'day');return {file,store};}
test('one clear empties only Today, preserving its undo across restart',()=>{let {file,store}=fixture();const before=structuredClone(store.data);store.clearToday(key);assert.deepEqual(store.read(key),emptyDay());assert.deepEqual(store.readProgress(key).extras,[]);assert.deepEqual(store.data.weeks,before.weeks);assert.deepEqual(store.data.months,before.months);assert.deepEqual(store.read('2026-09-06'),rows);store=new Store(file);assert.equal(store.canUndoToday(key),true);store.undoClearToday(key);assert.deepEqual(store.read(key),rows);assert.deepEqual(store.readProgress(key).extras,extras);assert.equal(store.canUndoToday(key),false);});
test('a failed clear or undo changes neither disk nor memory',()=>{const {file,store}=fixture();const before=fs.readFileSync(file,'utf8');fs.mkdirSync(file+'.tmp');assert.throws(()=>store.clearToday(key));assert.equal(fs.readFileSync(file,'utf8'),before);assert.deepEqual(store.read(key),rows);fs.rmdirSync(file+'.tmp');store.clearToday(key);const cleared=fs.readFileSync(file,'utf8');fs.mkdirSync(file+'.tmp');assert.throws(()=>store.undoClearToday(key));assert.equal(fs.readFileSync(file,'utf8'),cleared);assert.equal(store.canUndoToday(key),true);});
test('new Today edits retire undo rather than overwriting new work; other scopes do not',()=>{const {store}=fixture();store.clearToday(key);store.save('2026-09-07',emptyDay(),'week',[]);assert.equal(store.canUndoToday(key),true);store.clearToday(key);assert.equal(store.canUndoToday(key),true);const next=emptyDay();next[0].text='New work';store.save(key,next);assert.equal(store.canUndoToday(key),false);assert.throws(()=>store.undoClearToday(key));assert.deepEqual(store.read(key),next);assert.throws(()=>store.clearToday('bad-key'));});

test('v4 data stays unchanged until action, then backs up before upgrading',()=>{const {file,store}=fixture();const legacy={...store.data,version:4};delete legacy.clearUndo;const original=JSON.stringify(legacy);fs.writeFileSync(file,original);const upgraded=new Store(file);assert.equal(fs.readFileSync(file,'utf8'),original);upgraded.clearToday(key);assert.equal(fs.readFileSync(file+'.v4-backup','utf8'),original);assert.equal(new Store(file).canUndoToday(key),true);});
