const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store,dayKey,weekKey}=require('../src/store.cjs'),root=path.resolve(__dirname,'..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'three-clear-ui-')),out=path.join(root,'evidence-v092');fs.mkdirSync(out,{recursive:true});
const file=path.join(data,'priorities.json'),store=new Store(file),day=dayKey(),week=weekKey(),month=day.slice(0,7)+'-01';
const tasks=['Walk outside','Send the draft','Read a chapter'].map(text=>({text,done:true}));store.save(day,tasks,'day',[{text:'Water the plants',done:false}]);store.save(week,tasks,'week');store.save(month,tasks,'month');
const before=structuredClone(store.data),binary=process.env.THREE_THINGS_BINARY;let app,page;const errors=[];
async function launch(){app=await electron.launch({...(binary?{executablePath:binary,args:[]}:{args:[root]}),env:{...process.env,THREE_THINGS_TEST_DATA:data}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#priorities textarea',{state:'attached'});}
async function clear(){await page.locator('#clear-today').click();await page.waitForFunction(()=>[...document.querySelectorAll('#priorities textarea')].every(t=>t.value===''));assert.equal(await page.locator('#extras textarea').count(),0);assert.equal(await page.locator('#priorities input:checked').count(),0);assert.equal(await page.locator('#undo-clear-today').isVisible(),true);}
(async()=>{try{await launch();assert.equal(await page.locator('#clear-today').count(),1,'A visible one-click Clear today control exists');
await page.screenshot({path:path.join(out,'clear-before.png')});await clear();await page.screenshot({path:path.join(out,'clear-undo.png')});
await page.locator('#week-tab').click();assert.equal(await page.locator('#day-actions').isVisible(),false);assert.equal(await page.locator('#priorities input:checked').count(),3);await page.locator('#month-tab').click();assert.equal(await page.locator('#day-actions').isVisible(),false);await page.locator('#day-tab').click();assert.equal(await page.locator('#undo-clear-today').isVisible(),true);
await app.close();await launch();await page.locator('#undo-clear-today').click();await page.waitForFunction(()=>document.querySelectorAll('#priorities input:checked').length===3);assert.equal(await page.locator('#extras textarea').inputValue(),'Water the plants');assert.equal(await page.locator('.celebrate').count(),0);
fs.mkdirSync(file+'.tmp');await page.locator('#clear-today').click();await page.waitForSelector('#error:not([hidden])');assert.equal(await page.locator('#priorities input:checked').count(),3);fs.rmdirSync(file+'.tmp');await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelectorAll('#priorities input:checked').length===0);assert.equal(await page.locator('#undo-clear-today').isVisible(),true);
// Failed undo stays reversible, and retry performs the intended operation.
fs.mkdirSync(file+'.tmp');await page.locator('#undo-clear-today').click();await page.waitForSelector('#error:not([hidden])');assert.equal(await page.locator('#priorities input:checked').count(),0);fs.rmdirSync(file+'.tmp');await page.locator('#retry').click();await page.waitForFunction(()=>document.querySelectorAll('#priorities input:checked').length===3);
await clear();await page.locator('#priorities textarea').first().fill('A new first thing');await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Saved on this Mac');assert.equal(await page.locator('#undo-clear-today').isVisible(),false,'Undo never overwrites newly entered tasks');
// Empty state, Focus, narrow widths, keyboard, and both motion preferences.
for(const motion of ['reduce','no-preference']){await page.emulateMedia({reducedMotion:motion});for(const mode of ['list','focus']){await page.evaluate(mode=>window.threeThings.mode(mode),mode);for(const width of [320,390,760]){await app.evaluate(({BrowserWindow},{width,height})=>BrowserWindow.getAllWindows()[0].setSize(width,height),{width,height:mode==='focus'?370:440});const g=await page.locator('#day-actions').evaluate(e=>{const b=e.getBoundingClientRect();return {left:b.left,right:b.right,width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth};});assert(g.left>=0&&g.right<=g.width&&!g.overflow);await page.screenshot({path:path.join(out,'clear-'+mode+'-'+width+'-'+motion+'.png')});}}}
await page.locator('#clear-today').focus();await page.keyboard.press('Enter');await page.waitForSelector('#undo-clear-today:not([hidden])');await page.locator('#undo-clear-today').click();await page.waitForFunction(()=>document.querySelector('#priorities textarea').value==='A new first thing');
const invalid=await page.evaluate(()=>window.threeThings.clearToday('2000-01-01'));assert.equal(invalid.ok,false,'A stale day cannot be cleared');assert.equal(await page.locator('#priorities textarea').first().inputValue(),'A new first thing');
const after=new Store(file).data;assert.deepEqual(after.weeks,before.weeks);assert.deepEqual(after.months,before.months);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'clear-passed.json'),JSON.stringify({binary:binary||'source',passed:true}));console.log('PASS Clear today: one click, primary+extras, persistent undo, no overwrite of new work, isolated scopes, failed clear/undo retry, keyboard, small widths, Reduced Motion, stale-day guard, no repeated celebration');
}finally{await app?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
