const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Store}=require('../src/store.cjs'),{formatArchive}=require('../src/text-export.cjs');
const rows=done=>['Walk outside','Send the draft','Read a chapter'].map(text=>({text,done}));
const make=()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'three-finish-'));return {file:path.join(dir,'priorities.json'),dir};};
test('completion and optional tasks survive restart without changing the three',()=>{const {file}=make();const s=new Store(file);assert.equal(s.readProgress('2026-09-08').completedOnce,false);s.save('2026-09-08',rows(true));assert.equal(s.readProgress('2026-09-08').completedOnce,true);s.save('2026-09-08',rows(true),'day',[{text:'Water the plants',done:true}]);const t=new Store(file);assert.deepEqual(t.read('2026-09-08'),rows(true));assert.deepEqual(t.readProgress('2026-09-08'),{completedOnce:true,extras:[{text:'Water the plants',done:true}]});assert.match(formatArchive(t.data),/OPTIONAL EXTRA TASKS/);assert.match(formatArchive(t.data),/Water the plants/);});
test('undo and editing do not erase milestone or optional work; scopes stay separate',()=>{const {file}=make();const s=new Store(file);s.save('2026-09-08',rows(true),'day',[{text:'Stretch',done:false}]);s.save('2026-09-08',rows(false));assert.equal(s.readProgress('2026-09-08').completedOnce,true);assert.equal(s.readProgress('2026-09-08').extras.length,1);assert.deepEqual(s.readProgress('2026-09-07','week'),{completedOnce:false,extras:[]});assert.deepEqual(s.readProgress('2026-09-01','month'),{completedOnce:false,extras:[]});});
test('failed write cannot acknowledge completion or lose earlier state',()=>{const {file,dir}=make();const s=new Store(file);s.save('2026-09-08',rows(false));const before=fs.readFileSync(file,'utf8');fs.mkdirSync(file+'.tmp');assert.throws(()=>s.save('2026-09-08',rows(true)));assert.equal(s.readProgress('2026-09-08').completedOnce,false);assert.equal(fs.readFileSync(file,'utf8'),before);fs.rmdirSync(file+'.tmp');s.save('2026-09-08',rows(true));assert.equal(s.readProgress('2026-09-08').completedOnce,true);});
test('legacy completed lists migrate quietly and retain a byte-exact backup',()=>{const {file}=make();const old=JSON.stringify({version:3,days:{'2026-09-08':rows(true)},weeks:{},months:{}});fs.writeFileSync(file,old);const s=new Store(file);assert.equal(s.readProgress('2026-09-08').completedOnce,true);assert.equal(fs.readFileSync(file,'utf8'),old);s.save('2026-09-08',rows(true));assert.equal(fs.readFileSync(file+'.v3-backup','utf8'),old);});
test('extra tasks are validated and locked until three are complete',()=>{const {file}=make();const s=new Store(file);assert.throws(()=>s.save('2026-09-08',rows(false),'day',[{text:'Too soon',done:false}]));s.save('2026-09-08',rows(true));for(const extras of [[{text:'',done:true}],[{text:'x'.repeat(241),done:false}],Array(101).fill({text:'x',done:false})])assert.throws(()=>s.save('2026-09-08',rows(true),'day',extras));});
