const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=path.resolve(__dirname,'..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'three-fullscreen-')),out=path.join(root,'evidence-v010');fs.mkdirSync(out,{recursive:true});
const binary=process.env.THREE_THINGS_BINARY;let app,page;const errors=[];
async function launch(){app=await electron.launch({...(binary?{executablePath:binary,args:[]}:{args:[root]}),env:{PATH:process.env.PATH,HOME:os.homedir(),TMPDIR:os.tmpdir(),THREE_THINGS_TEST_DATA:data}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#priorities textarea',{state:'attached'});}
async function mode(m){await page.evaluate(m=>window.threeThings.mode(m),m);}
async function fullscreen(value){await page.evaluate(v=>window.threeThings.fullscreen(v),value);await page.waitForFunction(v=>document.documentElement.dataset.fullscreen===String(v),value);}
(async()=>{try{await launch();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreenable()),true,'The green Mac button must support real full screen');
for(let i=0;i<3;i++)await page.locator('#priorities textarea').nth(i).fill(['Take a walk before the day gets busy','Send the draft I have been putting off','Read a chapter before bed'][i]);await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Saved on this Mac');
const before=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds());
await app.evaluate(({Menu})=>Menu.getApplicationMenu().getMenuItemById('fullscreen').click());await page.waitForFunction(()=>document.documentElement.dataset.fullscreen==='true');await page.waitForTimeout(250);
assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),true);
for(const m of ['list','focus']){await mode(m);const g=await page.evaluate(()=>{const b=document.querySelector('main').getBoundingClientRect();return{width:b.width,center:b.x+b.width/2,screen:innerWidth,font:parseFloat(getComputedStyle(document.querySelector('#priorities textarea')).fontSize),overflow:document.documentElement.scrollWidth>innerWidth};});assert(g.width<=900&&Math.abs(g.center-g.screen/2)<2&&g.font>=26&&!g.overflow);await page.screenshot({path:path.join(out,'fullscreen-'+m+'.png')});}
await page.keyboard.press('Escape');await page.waitForFunction(()=>document.documentElement.dataset.fullscreen==='false');await page.waitForTimeout(100);assert.deepEqual(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds()),before);
await fullscreen(true);await mode('compact');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),false);assert.equal(await page.evaluate(()=>document.documentElement.dataset.mode),'compact');assert.equal(await app.evaluate(({Menu})=>Menu.getApplicationMenu().getMenuItemById('fullscreen').enabled),false);
await mode('list');await page.emulateMedia({reducedMotion:'reduce'});await fullscreen(true);await page.locator('#exit-fullscreen').click();await page.waitForFunction(()=>document.documentElement.dataset.fullscreen==='false');
await page.evaluate(()=>Promise.all([window.threeThings.fullscreen(true),window.threeThings.fullscreen(false)]));assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),false);
// Leaving full screen before quit must preserve normal window geometry on restart.
await fullscreen(false);await mode('list');const normal=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds());await fullscreen(true);await app.close();await launch();assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isFullScreen()),false);assert.deepEqual(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].getBounds()),normal);assert.equal(await page.locator('#priorities textarea').first().inputValue(),'Take a walk before the day gets busy');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'fullscreen-passed.json'),JSON.stringify({binary:binary||'source',passed:true,layouts:2}));console.log('PASS native fullscreen, native menu, List/Focus typography, Escape, previous bounds, Compact exit, Reduced Motion, rapid requests, restart, unchanged tasks; layouts:',2);
}finally{if(app){await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0]?.setFullScreen(false)).catch(()=>{});await app.close();}}})().catch(e=>{console.error(e);process.exitCode=1;});
