const {_electron:electron}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const root=path.resolve(__dirname,'..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'three-pass-')),out=path.join(root,'evidence-v09');fs.mkdirSync(out,{recursive:true});
const binary=process.env.THREE_THINGS_BINARY;let app,page;const errors=[];
async function launch(){app=await electron.launch({...(binary?{executablePath:binary,args:[]}:{args:[root]}),env:{...process.env,THREE_THINGS_TEST_DATA:data}});page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('textarea');}
async function size(width,height){await app.evaluate(({BrowserWindow},b)=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(b.width,b.height);},{width,height});await page.waitForTimeout(80);}
async function mode(m){await page.evaluate(m=>window.threeThings.mode(m),m);await page.waitForFunction(m=>document.documentElement.dataset.mode===m,m);}
async function saved(){await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='Saved on this Mac');}
async function shot(name){await page.screenshot({path:path.join(out,name+'.png')});}
(async()=>{try{await launch();for(let i=0;i<3;i++)await page.locator('#priorities textarea').nth(i).fill(['Walk outside before lunch','Send the revised draft','Read a chapter tonight'][i]);await saved();await mode('compact');await size(600,98);await shot('compact-before-or-after');const widths=await page.locator('#priorities .text-wrap').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().width));console.log('Compact text widths:',widths);assert(widths.every(x=>x>=120),'Compact task text must receive the flexible column, not 24px');
if(process.env.REPRO_ONLY)return;
for(const width of [600,760,1100]){await size(width,98);const boxes=await page.locator('#priorities .priority').evaluateAll(es=>es.map(e=>{const t=e.querySelector('.text-wrap').getBoundingClientRect(),c=e.querySelector('.check-wrap').getBoundingClientRect();return {text:t.width,gap:c.left-t.right,y:Math.abs(c.top-t.top)};}));assert(boxes.every(x=>x.text>=120&&x.gap>=0));await shot('compact-'+width);}
await page.locator('#priorities .text-wrap').nth(2).click();await page.waitForFunction(()=>document.documentElement.dataset.mode==='focus');assert.equal(await page.locator('#priorities .priority:not([hidden])').getAttribute('data-index'),'2');await page.waitForFunction(()=>document.querySelectorAll('#priorities textarea')[2]===document.activeElement);
await mode('list');await size(390,440);await page.locator('#priorities input[type=checkbox]').nth(0).check();await page.locator('#priorities input[type=checkbox]').nth(1).check();await saved();assert.equal(await page.locator('#finish').isVisible(),false);
// Force the real main-process store write to fail in this isolated profile.
fs.mkdirSync(path.join(data,'priorities.json.tmp'));
await page.locator('#priorities input[type=checkbox]').nth(2).check();await page.waitForSelector('#error:not([hidden])');assert.equal(await page.locator('#finish').isVisible(),false);assert.equal(await page.locator('.celebrate').count(),0);
fs.rmdirSync(path.join(data,'priorities.json.tmp'));await page.locator('#retry').click();await saved();await page.waitForSelector('#finish:not([hidden])');assert.equal(await page.locator('.celebrate').count(),1);const frames=[],start=Date.now();for(let i=0;i<10;i++){await shot('finish-frame-'+i);frames.push({file:'finish-frame-'+i+'.png',at:Date.now()-start});await page.waitForTimeout(100);}fs.writeFileSync(path.join(out,'motion-frames.json'),JSON.stringify(frames));await page.waitForFunction(()=>!document.querySelector('.celebrate'));await shot('completion-list');
await page.locator('#one-more').click();await page.locator('#extras textarea').fill('Water the plants');await saved();assert.equal(await page.locator('#priorities input:checked').count(),3);await page.locator('#extras input[type=checkbox]').check();await saved();await page.locator('#one-more').click();await page.locator('#extras textarea').nth(1).fill('Stretch for five minutes');await saved();await shot('optional-work');
await mode('compact');await size(600,98);await shot('compact-complete');assert.equal(await page.locator('#one-more').isVisible(),true);assert.equal(await page.locator('#extras').isVisible(),false);await page.locator('#one-more').click();await page.waitForFunction(()=>document.documentElement.dataset.mode==='list');await page.waitForFunction(()=>document.querySelectorAll('#extras textarea')[2]===document.activeElement);
await app.close();await launch();assert.equal(await page.locator('.celebrate').count(),0);assert.equal(await page.locator('#finish').isVisible(),true);assert.equal(await page.locator('#extras textarea').count(),3);assert.equal(await page.locator('#extras textarea').nth(1).inputValue(),'Stretch for five minutes');
await page.locator('#priorities textarea').first().fill('Walk outside in the morning');await page.locator('#priorities textarea').first().press('Enter');await saved();assert.equal(await page.locator('#priorities input:checked').count(),3);assert.equal(await page.locator('.celebrate').count(),0);
await page.locator('#priorities textarea').first().fill('');await page.locator('#priorities textarea').first().press('Tab');await saved();assert.equal(await page.locator('#priorities input:checked').count(),2);assert.equal(await page.locator('#finish-title').textContent(),'Optional work');assert.equal(await page.locator('#extras textarea').count(),3);
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#week-tab').click();for(let i=0;i<3;i++){await page.locator('#priorities textarea').nth(i).fill('Weekly priority '+(i+1));await page.locator('#priorities input[type=checkbox]').nth(i).check();}await saved();assert.equal(await page.locator('#finish').isVisible(),true);assert.equal(await page.locator('.celebrate').count(),0);assert.equal(await page.locator('#extras textarea').count(),0);
for(const m of ['list','focus']){await mode(m);for(const [w,h] of (m==='focus'?[[320,370],[390,390],[760,600]]:[[320,390],[390,440],[760,600]])){await size(w,h);const geometry=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,finish:document.querySelector('#finish').getBoundingClientRect().bottom,height:innerHeight}));assert.equal(geometry.overflow,false);await shot(m+'-'+w);console.log(m,w,h,geometry);assert(geometry.finish<=geometry.height,'Short completed list and finish must fit');}}
// Long and enlarged text remains readable through scrolling, not clipped editors.
await mode('list');await size(320,390);await page.locator('#month-tab').click();
for(let i=0;i<3;i++)await page.locator('#priorities textarea').nth(i).fill(('A longer priority with useful detail. ').repeat(7).slice(0,240));await saved();
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
assert.equal(await page.locator('#priorities textarea').evaluateAll(es=>es.every(e=>e.scrollHeight<=e.clientHeight+1)),true);
await page.evaluate(()=>document.documentElement.style.fontSize='150%');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await shot('long-enlarged-text');await page.evaluate(()=>document.documentElement.style.fontSize='');
await page.emulateMedia({reducedMotion:'no-preference'});for(let i=0;i<3;i++)await page.locator('#priorities input[type=checkbox]').nth(i).check();await saved();
await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>!document.querySelector('.celebrate'));
assert.equal(await page.evaluate(()=>document.querySelector('#finish').getBoundingClientRect().bottom<=innerHeight+1),true);
await page.locator('#week-tab').click();
// Native minimization stays separate from Mini and restores the same window.
await mode('compact');await app.evaluate(({BrowserWindow})=>new Promise((resolve,reject)=>{const w=BrowserWindow.getAllWindows()[0],timer=setTimeout(()=>reject(Error('Native minimize did not complete')),5000);w.once('minimize',()=>{clearTimeout(timer);resolve();});w.minimize();}));
assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMinimized()),true);
await app.evaluate(({Menu,BrowserWindow})=>new Promise((resolve,reject)=>{const w=BrowserWindow.getAllWindows()[0],timer=setTimeout(()=>reject(Error('Native restore did not complete')),5000);w.once('restore',()=>{clearTimeout(timer);resolve();});Menu.getApplicationMenu().getMenuItemById('show').click();}));
assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMinimized()),false);
// All backgrounds decode locally and keep the same Mini geometry.
await mode('list');await page.locator('#day-tab').click();
const catalog=require('../assets/appearance-catalog-v5.json');const results=[];for(const skin of catalog){await app.evaluate(({Menu},name)=>Menu.getApplicationMenu().getMenuItemById('skin-'+name).click(),skin.name);for(const m of ['list','focus','compact']){await mode(m);const bad=await page.evaluate(async()=>{const bg=getComputedStyle(document.querySelector('.app')).backgroundImage;const urls=[...bg.matchAll(/url\("?([^"\)]+)"?\)/g)].map(m=>m[1]);return await Promise.all(urls.map(url=>new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image.naturalWidth>0);image.onerror=()=>resolve(false);image.src=url;})));});assert(bad.every(Boolean),skin.name+' images decode');
const samples=await page.evaluate(()=>Array.from(document.querySelectorAll('textarea,.ink,.number,.completion-label,.periods button,#finish-title,#finish-count,#one-more,#compact-period,#expand,.window-actions button,#day-actions button')).filter(e=>e.checkVisibility()&&getComputedStyle(e).color!=='rgba(0, 0, 0, 0)').map(e=>{const b=e.getBoundingClientRect(),s=getComputedStyle(e);return {label:e.id||e.className,color:s.color,size:parseFloat(s.fontSize),x:b.x,y:b.y,width:b.width,height:b.height};}).filter(r=>r.x>=0&&r.y>=0&&r.y+r.height<=innerHeight));
await page.evaluate(()=>document.querySelectorAll('main,header').forEach(e=>e.style.opacity='0'));
const backdrop=skin.name+'-'+m+'-backdrop.png';await shot(backdrop.slice(0,-4));
await page.evaluate(()=>document.querySelectorAll('main,header').forEach(e=>e.style.opacity=''));
results.push({skin:skin.name,mode:m,backdrop,samples,viewport:await page.evaluate(()=>({width:innerWidth,height:innerHeight}))});}if(['graphite','meadow','linen'].includes(skin.name))await shot('background-'+skin.name);}
fs.writeFileSync(path.join(out,'collection.json'),JSON.stringify(results,null,2));assert.equal(results.length,catalog.length*3);assert.deepEqual(errors,[]);console.log('PASS layout, correct task focus, failed-save gating/retry, completion motion, optional tasks, restart, edits, reduced motion, scopes, sizes; background states:',results.length);
}finally{await app?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
